Description: 'AWS CloudFormation Template: Create KubeMaster and KubeWorker EC2 with EBS storage'

Parameters:
  KubeWorkerInstanceType:
    Description: EC2 KubeWorker instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.small
      - t2.medium

  VolumeSize:
    Description: Size of EBS
    Type: Number
    Default: 10

Resources:
  MyKubeMasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-08b91a65ed1075711
      Tags:
        - Key: "Name"
          Value: "MyKubeMaster"      
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:  
            VolumeSize: 15   
      KeyName: "Kube_master_Angular"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: "subnet-066a9b2dc7474e241"
      AvailabilityZone: "eu-west-1a"
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            sudo kubeadm init --cri-socket unix:///var/run/cri-dockerd.sock
            mkdir -p $HOME/.kube
            sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            sudo chown $(id -u):$(id -g) $HOME/.kube/config

            sudo systemctl restart kubelet
            sudo systemctl enable kubelet
            sudo kubeadm token create --print-join-command
            kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
            
  MyKubeWorkerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref KubeWorkerInstanceType
      ImageId: ami-08b91a65ed1075711
      Tags:
        - Key: "Name"
          Value: "MyKubeWorker"      
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: !Ref VolumeSize      
      KeyName: "Kube_master_Angular"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: "subnet-066a9b2dc7474e241"
      AvailabilityZone: "eu-west-1a"
