Description: 'AWS CloudFormation Template: Create KubeMaster and KubeWorker EC2 with EBS storage'

Parameters:
  KubeWorkerInstanceType:
    Description: EC2 KubeWorker instance type
    Type: String
    Default: t2.small
    AllowedValues:
      - t2.small
      - t2.medium

  VolumeSize:
    Description: Size of EBS
    Type: Number
    Default: 10

Resources:
  MyKubeMasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-0905a3c97561e0b69
      Tags:
        - Key: "Name"
          Value: "MyKubeMaster"      
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:  
            VolumeSize: 15   
      KeyName: "Kube_master_Angular"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: "subnet-066a9b2dc7474e241"
      AvailabilityZone: "eu-west-1a"

  MyKubeWorkerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref KubeWorkerInstanceType
      ImageId: ami-0905a3c97561e0b69
      Tags:
        - Key: "Name"
          Value: "MyKubeWorker"      
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: !Ref VolumeSize      
      KeyName: "Kube_master_Angular"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: "subnet-066a9b2dc7474e241"
      AvailabilityZone: "eu-west-1a"
