Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-0905a3c97561e0b69
      Tags:
        - Key: "Name"
          Value: "MyKubeMaster"
      KeyName: "Kube_master_Angular"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: "subnet-066a9b2dc7474e241"
      AvailabilityZone: "eu-west-1a"
