Description: 'AWS CloudFormation Template: Create KubeWorker EC2 with EBS storage'
  
Parameters:
  KubeWorkerInstanceType:
    Description: EC2 KubeWorker instance type
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.small
      - t3.medium

  WorkerInstanceCount:
    Type: Number
    Description: Number of KubeWorkers EC2 instances to create
    Default: 0

  MasterIP:
    Description: PublicIP of MasterNode
    Type: String

  SSHKey:
    Description: SSH Key for EC2 Instances
    Type: String
    #NoEcho: true
  
  VolumeSize:
    Description: Size of EBS
    Type: Number
    Default: 20

Resources:      
  MyKubeWorkerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref KubeWorkerInstanceType
      ImageId: ami-010c970cbbf22af42
      Tags:
        - Key: "Name"
          Value: !Sub "MyKubeWorker${WorkerInstanceCount}"     
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:
            VolumeSize: !Ref VolumeSize      
      KeyName: "KuberMaster"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: !ImportValue MyPublicSubnet1Id
          GroupSet: 
            - !ImportValue KubernetesSecurityGroup
      AvailabilityZone: "eu-north-1a"
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            echo "${SSHKey}"
            echo "${SSHKey}" > /home/ubuntu/encoded_key.pem
            ls -l
            sudo -u ubuntu base64 --decode /home/ubuntu/encoded_key.pem > /home/ubuntu/Kube_master_Angular.pem
            ls -l
            sudo chmod 777 /home/ubuntu/Kube_master_Angular.pem
            sudo -u ubuntu scp -o StrictHostKeyChecking=no -i /home/ubuntu/Kube_master_Angular.pem ubuntu@${MasterIP}:/home/ubuntu/join.txt /home/ubuntu/.
            sudo -u ubuntu mkdir /home/ubuntu/.kube
            sudo -u ubuntu scp -o StrictHostKeyChecking=no -i /home/ubuntu/Kube_master_Angular.pem ubuntu@${MasterIP}:/home/ubuntu/.kube/config /home/ubuntu/.kube/config
            joinCommand=$(cat /home/ubuntu/join.txt)
            fullCommand="sudo -u ubuntu sudo $joinCommand --cri-socket unix:///var/run/cri-dockerd.sock"
            eval $fullCommand
            sudo -u ubuntu kubectl rollout restart deployment/coredns -n kube-system

          #  FIRST_INSTANCE_IP="${FirstInstancePublicIP}"
         #   sudo ssh -o StrictHostKeyChecking=no -i Kube_master_Angular.pem ubuntu@${FIRST_INSTANCE_IP}
         #   scp ubuntu@${FIRST_INSTANCE_IP}:join.txt .