Description: 'AWS CloudFormation Template: Create KubeMaster EC2 with EBS storage'
Resources:
  KubernetesIAMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - KubernetesIngressRole

  MyKubeMasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: ami-0c71414824378efab
      IamInstanceProfile: 
        Ref: KubernetesIAMInstanceProfile
      Tags:
        - Key: "Name"
          Value: "MyKubeMaster"      
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:  
            VolumeSize: 10   
      KeyName: "KuberMaster"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: !ImportValue MyPublicSubnet1Id
          GroupSet: 
            - !ImportValue KubernetesSecurityGroup
      AvailabilityZone: "eu-north-1a"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo -u ubuntu sudo kubeadm init --cri-socket unix:///var/run/cri-dockerd.sock

            sudo -u ubuntu sudo systemctl restart kubelet
            sudo -u ubuntu sudo systemctl enable kubelet

            sudo -u ubuntu mkdir -p /home/ubuntu/.kube
            sudo -u ubuntu sudo cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
            sudo -u ubuntu sudo chown ubuntu /home/ubuntu/.kube/config
            sudo -u ubuntu sudo chmod 777 /home/ubuntu/.kube/config

            sudo -u ubuntu kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.2/manifests/calico.yaml
            sudo -u ubuntu kubeadm token create --print-join-command > /home/ubuntu/join.txt
            cd /home/ubuntu/
            sudo -u ubuntu git clone https://github.com/fanfanafankianki/KubeServices
            sudo -u ubuntu kubectl rollout restart deployment/coredns -n kube-system && sleep 10
            echo "REGION: ${AWS::Region}, INSTANCE_ID: $(curl http://169.254.169.254/latest/meta-data/instance-id), PRIVATE_IP: $(curl http://169.254.169.254/latest/meta-data/local-ipv4), PROVIDER_ID: aws:///${AWS::Region}/$(curl http://169.254.169.254/latest/meta-data/instance-id)"
            sudo -u ubuntu kubectl patch node "ip-$(curl http://169.254.169.254/latest/meta-data/local-ipv4 | tr '.' '-')" -p "{\"spec\":{\"providerID\":\"aws:///${AWS::Region}/$(curl http://169.254.169.254/latest/meta-data/instance-id)\"}}"
            if [ $? -eq 0 ]; then
                echo "Polecenie patch zakończone sukcesem."
            else
                echo "Polecenie patch zakończone błędem."
            fi
            cd /home/ubuntu/KubeServices/
            sudo -u ubuntu git checkout HelmPromGraf
            cd /home/ubuntu/KubeServices/Kubernetes_Yamls/
            sudo -u ubuntu kubectl apply -f /home/ubuntu/KubeServices/Kubernetes_Yamls/.
            sudo -u ubuntu kubectl apply -f /home/ubuntu/KubeServices/Kubernetes_Yamls/NFS_configuration/.
            sudo -u ubuntu curl -s https://fluxcd.io/install.sh | sudo bash
            echo "export GITHUB_TOKEN='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'" | sudo tee -a /home/ubuntu/.bashrc > /dev/null
            sudo -u ubuntu kubectl rollout restart deployment/coredns -n kube-system && sleep 10
            sudo -u ubuntu flux bootstrap github   --owner=fanfanafankianki   --repository=KubeServices   --branch=HelmPromGraf   --path=./Flux_configuration   --personal

            sudo -u ubuntu kubectl rollout restart deployment/coredns -n kube-system && sleep 10
            sudo -u ubuntu helm repo add bitnami https://charts.bitnami.com/bitnami
            sudo -u ubuntu helm repo add eks https://aws.github.io/eks-charts
            sudo -u ubuntu helm repo update
            sudo -u ubuntu helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
                --namespace kube-system \
                --set clusterName=kubernetes \
                --set serviceAccount.create=true \
                --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::975050111074:role/KubernetesIngressRole

            sudo -u ubuntu kubectl rollout restart deployment/coredns -n kube-system && sleep 30
            sudo -u ubuntu helm install external-dns bitnami/external-dns \
              --namespace kube-system \
              --set provider=aws \
              --set aws.zoneType=public \
              --set domainFilters[0]=powertrckr.com \
              --set policy=sync \
              --set registry=txt \
              --set txtOwnerId=kubemaster \
              --set interval=1m

Outputs:
  InstanceProfileOutput:
    Description: "The ARN of the Instance Profile"
    Value: !Ref KubernetesIAMInstanceProfile
    Export:
      Name: KubernetesIAMInstanceProfile

