Description: 'AWS CloudFormation Template: Create KubeMaster EC2 with EBS storage'

Resources:
  MyKubeMasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-08b91a65ed1075711
      Tags:
        - Key: "Name"
          Value: "MyKubeMaster"      
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:  
            VolumeSize: 10   
      KeyName: "Kube_master_Angular"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: "subnet-066a9b2dc7474e241"
          GroupSet:
            - sg-0a2b0e2ce3bc7bf54
      AvailabilityZone: "eu-west-1a"
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            sudo kubeadm init --cri-socket unix:///var/run/cri-dockerd.sock

            sudo systemctl restart kubelet
            sudo systemctl enable kubelet

            mkdir -p $HOME/.kube
            sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            sudo chown $(id -u):$(id -g) $HOME/.kube/config
            
            kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
            echo "Zapisujeee!!!!"
            sudo kubeadm token create --print-join-command > /home/ubuntu/join.txt



