Description: 'AWS CloudFormation Template: Create KubeMaster EC2 with EBS storage'

Resources:
  MyKubeMasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.medium
      ImageId: ami-010c970cbbf22af42
      Tags:
        - Key: "Name"
          Value: "MyKubeMaster"      
      BlockDeviceMappings:
        - DeviceName: "/dev/sda1"
          Ebs:  
            VolumeSize: 10   
      KeyName: "KuberMaster"
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          DeleteOnTermination: true
          SubnetId: !ImportValue MyPublicSubnet1Id
          GroupSet: 
            - !ImportValue KubernetesSecurityGroup
      AvailabilityZone: "eu-north-1a"
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash
            sudo -u ubuntu sudo kubeadm init --cri-socket unix:///var/run/cri-dockerd.sock

            sudo -u ubuntu sudo systemctl restart kubelet
            sudo -u ubuntu sudo systemctl enable kubelet

            sudo -u ubuntu mkdir -p /home/ubuntu/.kube
            sudo -u ubuntu sudo cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
            sudo -u ubuntu sudo chown ubuntu /home/ubuntu/.kube/config
            sudo -u ubuntu sudo chmod 777 /home/ubuntu/.kube/config

            sudo -u ubuntu kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
            sudo -u ubuntu kubeadm token create --print-join-command > /home/ubuntu/join.txt



